const completeReservedNames = {
    // Globální objekty z window
    globals: [
        'destovkaStepManager',
        'destovkaTankManager',
        'destovkaCart',
        'destovkaAccessoryFilter',
        'destovkaAccessoryManager',
        'destovkaAccessoriesManager',
        'destovkaSidebar',
        'destovkaKonfigCalculator',
        'destovkaCartDisplay',
        'destovkaCartDisplayIntermediate',
        'productStructureGenerator',
        'unitConverter',
        'volumeRange',
        'tooltipHandler',
        'urlStateManager',
        'destovkaTankFilter',
        'destovkaFiltrationManager',
        'destovkaSiphonManager',
        'destovkaPumpManager',
        'destovkaPumpAccessoryManager',
        'destovkaHladinomeryManager',
        'destovkaGeigeryManager',
        'destovkaPotrubíManager',
        'destovkaVsakovaciManager',
        'destovkaCalculatorVsakObjem',
        'destovkaExtensionCalculator',
        'DESTOVKA_CONFIG',
        'destovka_cart'
    ],
    
    // Třídy
    classes: [
        'DestovkaStepManager',
        'DestovkaTankManager',
        'DestovkaCart',
        'DestovkaAccessoryFilter',
        'DestovkaAccessoryManager',
        'DestovkaAccessoriesManager',
        'CartStructureGenerator',
        'ProductStructureGenerator',
        'VolumeRangeHandler',
        'UnitConverter',
        'TooltipHandler',
        'DestovkaKonfigCalculator',
        'DestovkaTankFilter',
        'DestovkaCartDisplayManager',
        'UrlStateManager',
        'ExtensionCalculator',
        'DestovkaFiltrationManager',
        'DestovkaBaseProductManager',
        'DestovkaSiphonManager',
        'DestovkaPumpManager',
        'DestovkaPumpAccessoryManager',
        'DestovkaHladinomeryManager',
        'DestovkaGeigeryManager',
        'DestovkaPotrubíManager',
        'DestovkaCalculatorVsakObjem',
        'VsakovaciCalculator',
        'DestovkaVsakovaciManager',
        'CoverCalculator'
    ],
    
    // Všechny metody
    methods: [
        // DestovkaCart metody
        'destAddItem',
        'destRemoveItem',
        'destGetItemsByStep',
        'destGetAllItems',
        'destClear',
        'destSaveToStorage',
        'destLoadFromStorage',
        'destExportForURL',
        'destImportFromURL',
        'destUpdateQuantity',
        'destGetTotalPrice',
        'destAddBatch',
        'destValidateStepLimit',
        
        // Veřejné metody
        'showEmailPopup',
        'handleAddToCart',
        'showAccessoryPopup',
        'updateTankDisplay',
        'handleNextStep',
        'handlePreviousStep',
        'changeStep',
        'initializeSelection',
        'initializeCategorySelection',
        'getSelectedProducts',
        'calculateBoxLayout',
        'calculateMinArea',
        'calculateMinVolume',
        
        // Callback funkce
        'handleCategorySelection',
        'handleConfirm',
        'handleSkip',
        'handleError',
        'validateStep',
        'saveFormData',
        'restoreFormData',
        'updateDisplay',
        'renderTanks',
        'renderCart',
        'initializeEventListeners',
        'initializeValidation',
        'updateButtonsState',
        'showCategories',
        'closePopup',
        'showNoResults',
        'formatPrice',
        'formatAvailability',
        'extractPrice',
        'updateTotalPrice',
        'sendEmailData',
        'loadXMLFeed',
        'processUrlParameters',
        
        // Inicializační metody
        'initializeConfigurator',
        'initializeRemainingStepsCounter',
        'initializeNatokToggle',
        'initProductContainer',
        'initializeContainers',
        'initializeUnitButtons',
        'initializeDetailsToggle',
        'initializeCounters',
        'initializeInputHandlers',
        'initializeVsakBoxGridControls',
        'initializeVsakBoxCounters',
        
        // Kalkulační metody
        'calculateTankScore',
        'calculateEarthworksScore',
        'calculateVolumeScore',
        'calculateLoadScore',
        'calculateRecommendedJimka',
        'calculateRecommendedTunel',
        'calculateBoxLayout',
        'calculateVsakValues',
        'calculateActualJimkaValues',
        'calculateActualTunnelValues',
        'calculateActualBoxValues',
        'calculateExtensions',
        'calculateTotals',
        'calculateDepth',
        
        // Filtrovací a validační metody
        'filterTanks',
        'filterProducts',
        'passesCriticalFilters',
        'passesLoadCheck',
        'passesVolumeCheck',
        'passesDNCheck',
        'passesEarthworksCheck',
        'passesExtensionCheck',
        'getCompatibleAccessories',
        'getCompatibleExtensions',
        'getCompatibleCovers',
        
        // Render metody
        'renderNoResults',
        'renderEmptyCart',
        'renderError',
        'renderSteps',
        'updateGridVisualization',
        
        // Form handling
        'convertToMM',
        'convertFromMM',
        'updateValue',
        'updateRemainingHeight',
        'updateDetailValues',
        
        // Fetch/Load metody
        'loadWithRetry',
        'fetchWithRetry',
        'loadFiltrationData',
        'loadSiphonData',
        'loadPumpsData',
        'loadAccessoryData',
        'loadHladinomeryData',
        'loadGeigerData',
        'loadPotrubíData',
        'loadMatrixData',
        'loadExtensionData',
        'loadCoverData',
        
        // Event handlery
        'handleCoverSelection',
        'handleDetailsToggle',
        'handleUnitChange',
        'processItems',
        'processProductUrl',
        
        // Helper metody
        'extractMinutes',
        'getElementText',
        'getSelectedProduct',
        'getSelectedGeigers',
        'showStepsSelectionPopup',
        'createTankElement',
        'addItemToCart',
        'formatPumpSpecs',
        'formatPotrubiPrice',
        'groupPotrubíByColumns',
        'generateSpecsRows',
        'getPluralForm'
    ],
    
    // DOM ID
    domIdentifiers: [
        'destovka-step1',
        'destovka-step2',
        'destovka-step3',
        'destovka-step4',
        'destovka-step5',
        'destovka-step6',
        'destovka-step7',
        'destovka-step7-5',
        'destovka-step8',
        'destovka-step9',
        'destovka-step10',
        'destovka-step11',
        'destovka-step12',
        'volumeRange',
        'volumeValue',
        'concrete',
        'soil',
        'hsvDepth',
        'load',
        'inflowDiameter',
        'outflowDiameter',
        'inflowDepth',
        'distance',
        'rainfallStation',
        'destovkaTanksContainer',
        'destovkaAccessoriesContainer',
        'destovka-distance-group',
        'destovka-direct-depth',
        'destovka-email-name',
        'destovka-email-address',
        'destovka-email-phone',
        'destovka-email-gdpr',
        'destovka-email-send',
        'stepsList'
    ],
    
    // CSS třídy
    cssClasses: [
        'destovka-active',
        'destovka-selected',
        'destovka-product-selected',
        'destovka-tank-box-selected',
        'destovka-product-card',
        'destovka-tank-box',
        'destovka-button',
        'destovka-button-next',
        'destovka-button-back',
        'destovka-input-error',
        'destovka-label-error',
        'destovka-error-banner',
        'destovka-fade-out',
        'destovka-input',
        'destovka-input-row',
        'destovka-tooltip',
        'destovka-product-recommended',
        'destovka-category-selected',
        'destovka-empty-product',
        'destovka-product-unavailable',
        'destovka-availability-instock',
        'destovka-availability-outstock',
        'destovka-volume-warning'
    ],
    
    // URL parametry
    urlParams: [
        'volume',
        'volumeRange',
        'concrete',
        'soil',
        'hsvDepth',
        'load',
        'inflowDiameter',
        'outflowDiameter',
        'inflowDepth',
        'rainfallStation',
        'distance',
        'step',
        'p0', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9',
        'q0', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9'
    ],
    
    // Data atributy
    dataAttributes: [
        'data-code',
        'data-product-code',
        'data-tank-code',
        'data-dimension',
        'data-current-unit',
        'data-height',
        'data-category',
        'data-system',
        'data-type',
        'data-missing',
        'data-tank-id'
    ],
    
    // JSON klíče z API
    jsonKeys: [
        'Kód',
        'Název',
        'Produkt',
        'Systém',
        'Objem (l)',
        'Konstrukce',
        'Zatížení',
        'Zatizeni1',
        'Zatizeni2',
        'Zatizeni3',
        'Hloubka nátoku bez nástavce (mm)',
        'Max. překrytí zeminou (mm)',
        'DN100/110',
        'DN125',
        'DN150/160',
        'Integrovaný bezpečnostní přepad (sifon)',
        'Kategorie',
        'Typ',
        'Barva',
        'Výška (mm)',
        'Minimální výška (mm)',
        'Maximální výška (mm)',
        'Marze (%)',
        'Záruka (let)',
        'PříslušenstvíID1',
        'PříslušenstvíID2',
        'PříslušenstvíID3'
    ],
    
    // Externí API
    externalAPIs: [
        'dataLayer',
        'shoptet',
        'shoptet.cartShared',
        'shoptet.cartShared.addToCart',
        'fetch',
        'XMLHttpRequest',
        'DOMParser',
        'localStorage',
        'MutationObserver'
    ],
    
    // Map objekty a jejich metody
    mapProperties: [
        'feedData',
        'formData',
        'tanksData',
        'filtraceData',
        'siphonData',
        'pumpsData',
        'accessoryData',
        'hladinomeryData',
        'geigerData',
        'potrubíData',
        'matrixData',
        'extensionsData',
        'coversData',
        'resultMap',
        'destStepLimits'
    ],
    
    // Konstanty
    constants: [
        'MAX_RETRIES',
        'RETRY_DELAY',
        'inflowOffsetFromTop',
        'soilCoefficients',
        'infiltrationCoefficients',
        'loadHierarchy',
        'categories',
        'sidebarSteps',
        'typeToImageCode',
        'categoryImages',
        'categoryDescriptions',
        'categoryDescriptions2'
    ],
    
    // Event názvy
    eventNames: [
        'DOMContentLoaded',
        'input',
        'change',
        'click',
        'mouseenter',
        'scroll',
        'keydown'
    ],
    
    // Query selectory
    querySelectors: [
        '.destovka-product-selected',
        '.destovka-product-card',
        '.destovka-tank-box',
        '.destovka-button-next',
        '.destovka-button-back',
        '.destovka-quantity-input',
        '.destovka-unit-button',
        '.destovka-toggle-natok',
        '.destovka-no-results',
        '.destovka-error-message',
        '.destovka-cart-content',
        '.destovka-products-container',
        '.destovka-categories-container',
        '.destovka-main-container'
    ],
    
    // Speciální objekty
    specialObjects: [
        'activeSteps',
        'weights',
        'volumeToleranceStep',
        'initialVolumeTolerance',
        'maxVolumeTolerance',
        'vsakovaciJimkaCodes',
        'vsakovaciTunelCodes',
        'dataLayer[0].shoptet.cart'
    ],
    
    // JSON/API paths
    apiPaths: [
        'g:id',
        'g:price',
        'g:availability',
        'g:image_link',
        'title',
        'link',
        'entry',
        'feed',
        'channel'
    ]
};

module.exports = { completeReservedNames };